### ISSUE TITLE
Problem Running Taudem

### ISSUE THREAD

**Issue by skoelker** [dtarb/TauDEM#115]
**Hello,

i have installed the Taudem version 3.5.7 Version on my computer and the arcmap version 10.3.1. I just tried to run the pitremove tool, but it doesn't work. As soon as I drop the tif-data into the field "input elevation grid" I get the following error:**

ERROR 
updateParameters Execution Error: Runtime error Traceback (most recent call last): File "C:\Program Files\TauDEM\TauDEM5Arc\TauDEM Tools.tbx#PitRemove.UpdateParameters.py", line 4, in File "C:\Program Files\TauDEM\TauDEM5Arc\TauDEM Tools.tbx#PitRemove.UpdateParameters.py", line 28, in updateParameters UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 72: ordinal not in range(128) 

**I also tried to run the Taudem tool in qgis but it also didn't work. There I get the following error:**

2017-02-22T19:11:09	1	warning:C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python/plugins\processing\core\GeoAlgorithm.py:219: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6  unicode(e.message, errors='replace') + self.tr('\nSee log for more details'), lines, e) traceback:  File C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python/plugins\processing\gui\ProcessingToolbox.py", line 256, in executeAlgorithm dlg.exec_() File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 290, in accept if runalg(self.alg, self): File C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 49, in runalgalg.execute(progress or SilentProgress())

I tried to install different versions of taudem but none works. Everytime I get the above mentioned error. Could you help me to fix the problem?

Kind regards
Stephanie Kölker

**Comment by dtarb** [comment]
The culprit seems most likely the umlaut (two dots on o) in your name which may be in the file name path.  Sorry to be special character unfriendly.  The python code that parses file names treats them as ASCII, but fails with special characters.  I'd like to fix this sometime.  Until then the workaround is to try put the files in a folder without special characters in the name.  You could also try run the programs from a command line, but that is less convenient.

I am not sure what the QGIS problem is.

Feel free to respond again of these do not help.

**Comment by skoelker** [comment]
Thank you for you help. The problem isn't the path way. I read before that there may be problems with äöü " " and the different other umlauts. Hence I created the pathway C://Taudem. A shorter pathway isn't possbile. Running the TauDem Programm in the windows command line doesn't work, too. This delivers the following error: 
![image](https://cloud.githubusercontent.com/assets/25962037/23249754/2f8a40be-f9a6-11e6-9912-4e3d183ce6be.png)
It says that the DLL SSLEAY32.dll isn't found from the GDAL. I'm wondering if I have to install additional software on my computer? I used the all in windows installer and followed you installing instructions. Are there more preconditions for installing Taudem?

**Comment by skoelker** [comment]
I just tried to solve the problem renaming all programm files. Now its possible to upload the input data set into the Tool "PitRemove". Nevertheless the programm is still not running. Now I get the following message:

![grafik](https://cloud.githubusercontent.com/assets/25962037/23254966/22af6f22-f9ba-11e6-9cf1-9fb8d473275f.png)

**Comment by dtarb** [comment]
The complete installer you used should install all the dependencies needed.  I think though that with name/path changes they may not be found, or there may be interfering dll's on your system.  I found that on my system SSLEAY32.dll is in lots of places including GDAL.  If the dll from a different program is being found first it may be a problem and path alterations may have caused this.

One way to check whether GDAL is properly installed may be to from the command line use "where gdal_translate" and "gdal_translate" on one of your data files to see if you can write it to a different format.

To be sure what is going on with the arcGIS functions I would need to see the text higher up in the window than you have shown.  There is a mpiexec -n 8 pitremove command that is sent to the system and I would want to see it, its file path arguments, and the response to it.  Is it generating the same dll ordinal not found error, or something else.

**Comment by skoelker** [comment]
![grafik](https://cloud.githubusercontent.com/assets/25962037/23259145/f336a352-f9cb-11e6-8e9d-224fcce9caba.png)

**Comment by skoelker** [comment]
![grafik](https://cloud.githubusercontent.com/assets/25962037/23259174/171413ae-f9cc-11e6-9a5b-127f2b290617.png)

This is the message arcmap delivers to me. I installed QGIS and Taudem on another Pc, but there it isn't running, too. QGis says there that the "mpiexec" isn't found.

**Comment by dtarb** [comment]
This will be best to debug using a command line.  The TauDEM function is not producing any output so most likely not getting found/started. Try type "where mpiexec" to see if your system has MPI installed and path correct.  If this works try type the whole command mpiexec -n 8 -z ... with your file names to see what happens.  

Both ArcGIS and QGIS interfaces construct a command line instruction to run, so if command line programs are not running neither will work.

**Comment by skoelker** [comment]
My system can't find mpiexec file. Running the programm in windows command line works, too. The commands are a little bit different in writing than mentioned on your homepage for mpiexec but it works.
Thank you for you help!

**Comment by dtarb** [comment]
Look for an entry PATH=C:\Program Files\Microsoft MPI\Bin\ near the beginning of your path.  This should have been set when you installed Microsoft MPI.  The install file that the complete install used was from https://www.microsoft.com/en-us/download/details.aspx?id=52981.  It may help to try install this directly.

**Comment by ricardotavarescosta** [comment]
Dear all,

first of all thank you for the development of this software and its parallelisation. It is benefiting a lot my research, and I am sure of many others like me.

I am writing this email because I am in need to understand how to achieve better performances. I have been running taudem over the cloud (Amazon EC2‎) and I have tried several machine configurations up to 126 cores and 500gb ram...

Then I came across your paper:

http://hydrology.usu.edu/dtarb/Survila_XSEDE_2016_a11.pdf <http://hydrology.usu.edu/dtarb/Survila_XSEDE_2016_a11.pdf>

and it got me really intrigued, because you report extraordinary performances:

“Experiments show that then enhanced parallel D8 algorithm significantly outperforms the current TauDEM version. Before, it took days for D8 to process a 36GB DEM. Now we are able to process a 67GB compressed DEM within two minutes.”

the raster I am using is in the order of size of the one you report in Figure 7 (11.3Gb) although with the double of the number of flats, and my D8 computation is projected to take days (already in day 3).

Could you give me some feedback on how to improve this? Am I using a version of Taudem which still does not have your latest upgrades to the algorithms and best parallelisation? Am I using the wrong compiler or I need to include specific compiler options?

Thank you in advance,

Ricardo Tavares da Costa <mailto:ricardotavarescosta@gmail.com>, PE PhD Fellow, GECOsistema srl
0039 392113 <tel:+351 96 369 6337>5329 • @rtavarescosta <https://twitter.com/rtavarescosta>
 <https://it.linkedin.com/in/ricardotavarescosta> <https://www.researchgate.net/profile/Ricardo_Tavares_da_Costa>

**Comment by dtarb** [comment]
The code in this repository (https://github.com/dtarb/TauDEM) does not (yet) have the improvements that Kornelijus implemented and reported in the XSEDE paper.  Kornelijus' code is in https://github.com/kornholi/TauDEM.

It is my intention to merge the two forks together, but there were some result differences that I wanted to track down before merging, and also a different way of handling partition memory that required additional dependencies that needed some sorting out.  These details and lack of time have led to this not being merged yet.

**Comment by ricardotavarescosta** [comment]
Dear Prof. Tarboton,
 
thank you very much for your reply, I will have a look at Kornelijus’ work. If I can be of some help, please let me know I am happy to contribute.

Ricardo

**Comment by lworcel** [comment]
Dear David Tarboton,

I have the same problem to execute the Taudem algorithms that skoelker. In ArcGis, in Q-Gis. (in windows). On 3 different machines. Also, I tried to run it on Linux OsGeo ... With the same luck.
For months I tried to solve it without luck. I need your help. Is it necessary to install the MPI first and then the Taudem? I have nothing installed with strange characters. I do not know what to do. I hope you can help me. Thank you!
