### ISSUE TITLE
error running TWI

### ISSUE THREAD

**Issue by dbrien** [dtarb/TauDEM#169]
Hello,
I am using TauDEM version 5.2 ArcToolBox tools and most of the tools work fine, but I receive an error message when I run TWI.  Here is an excerpt from the ourput window, including the error message I receive:

Command Line: mpiexec -n 8 TWI -sca "D:\micronesia3Chuuk\junkTWI\wenonew2sca.tif" -slp "D:\micronesia3Chuuk\junkTWI\wenonew2slp.tif" -twi "D:\micronesia3Chuuk\junkTWI\wenonew2twi.tif"

Process started:
Executing: Calculate Statistics
Failed script TopographicWetnessIndex...

Traceback (most recent call last):
  File "C:\Program Files\TauDEM53\TauDEM5Arc\TopographicWetnessIndex.py", line 47, in <module>
    arcpy.CalculateStatistics_management(twi)
  File "c:\arcgis\desktop10.3\arcpy\arcpy\management.py", line 14618, in CalculateStatistics
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Raster Dataset: Dataset D:\micronesia3Chuuk\junkTWI\wenonew2twi.tif does not exist or is not supported
Failed to execute (CalculateStatistics).
Failed to execute (TopographicWetnessIndex).

Let me know if you have any suggestions.  Thanks.
Dianne Brien

**Comment by dtarb** [comment]
Try open a command prompt and run the command line function
>mpiexec -n 8 TWI -sca "D:\micronesia3Chuuk\junkTWI\wenonew2sca.tif" -slp "D:\micronesia3Chuuk\junkTWI\wenonew2slp.tif" -twi "D:\micronesia3Chuuk\junkTWI\wenonew2twi.tif"
This should give error messages that help with the problem.  

Is there a reason you are not running one of the later versions (latest is 5.3.7).  I am puzzled by the statement you are running version 5.2 from ArcToolbox, because version 5.2 was a multifile version that did not have an ArcToolbox and the multifile approach it used has been discontinued in favor of using GDAL.

**Comment by dbrien** [comment]
Sorry the 5.2 was a typo - I am using version 5.3.  When running via command line, I receive a window with the error 'The procedure entry point SPLite3_last_insert_rowid could not be located in the dynamic link library spatiallite.dll'
Here is a screen shot of the error :
![image](https://user-images.githubusercontent.com/26911185/39317499-909fa1ac-4930-11e8-848b-94a4370065cb.png)

Dianne

**Comment by dbrien** [comment]
I thought I would try uninstalling and reinstalling TauDEM.  Although I received an error regarding installation of MS-MPI, the TauDEM tools, including TWI, seem to be working for me now.
-Dianne

**Comment by dtarb** [comment]
Glad it is running.  I thought I would add that the spatialite.dll is part of GDAL and the error would suggest something incorrect with the GDAL installation, or other software on the system that also uses spatialite,dll but perhaps a different and incompatible version.  Apparently reinstallation fixed this.  I hope the MS-MPI does not give you trouble.  If it does, it is possible to install the dependencies separately, and you may need to resort to that.
