### ISSUE TITLE
D8 Contributing Area Aborted

### ISSUE THREAD

**Issue by Jezzpeth** [dtarb/TauDEM#184]
Greetings,
   I have been attempting to run the "D8 Contributing Area" tool. I have a point feature file for "input outlets" and a precipitation weight grid. The weight grid and the flow direction grid have identical resolutions, and the projected coordinate systems match. The tool seems to have an issue with both of the optional files. If I only run the tool with the outlet file (but not the precipitation), I get the following error:

![contarea1_withnoprecip](https://user-images.githubusercontent.com/42077836/43739235-90c18962-9984-11e8-988f-01db9d613418.jpg)

And if I run the tool with the precipitation file (but not the outlet), I get the following error:

![contarea2_wnooutlet](https://user-images.githubusercontent.com/42077836/43739238-92ffd756-9984-11e8-80ee-044c2fb7d2a1.jpg)

Note that the tool will run just fine if I remove both of the optional files (outlets + precip).

Any suggestions are much appreciated. Thank you!

**Comment by dtarb** [comment]
For the first problem check the value of the flow direction at the outlet point.  It may be no data (due to near edge or area where DEM is no data).  

For both problems try use .tif files for the output result.  I do not think TauDEM can write ESRI grids, which is what would be implied by a file name without extension.  Though it may default to tif in those cases.  To be more specific, I would need to look in the code to to see where error 5 is generated (or you could try look).

**Comment by Jezzpeth** [comment]
Thank you, the outlet file issue has been fixed. I made sure that .tif files were specified for the outlet result, but that has not fixed the problem when I try to use a precipitation (TIFF) file as a weight grid. I have pasted the error codes if I run the tool via IDLE or the command line below. Did you need info from elsewhere (I am a beginner at coding)?

Error via IDLE: 
Traceback (most recent call last):
  File "F:/DissAnalysis_2018/PythonScripts/ContArea_only.py", line 14, in <module>
    arcpy.gp.D8ContributingArea(CondDEM_FlowD8_2_tif, "", prec09_clp_TIFF, "true", "8", testing_precip_again)
  File "C:\Program Files (x86)\ArcGIS\Desktop10.6\ArcPy\arcpy\geoprocessing\_base.py", line 510, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
ExecuteError: 
Traceback (most recent call last):
  File "C:\Program Files\TauDEM\TauDEM5Arc\D8ContributingArea.py", line 96, in <module>
    arcpy.CalculateStatistics_management(ad8)
  File "C:\Program Files (x86)\ArcGIS\Desktop10.6\ArcPy\arcpy\management.py", line 17042, in CalculateStatistics
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Raster Dataset: Dataset F:\DissAnalysis_2018\Hydrology\2018processes\RESULTS\testing_precip_again.tif does not exist or is not supported
Failed to execute (CalculateStatistics).


Failed to execute (D8ContributingArea).

-------------------Error via command line------------------------------------------
C:\Users\capib>mpiexec -n 8 AreaD8 -p "F:\DissAnalysis_2018\Hydrology\2018processes\RESULTS\CondDEM_FlowD8_2.tif" -ad8 "F:\DissAnalysis_2018\Hydrology\2018processes\RESULTS\ContArea_testing_again.tif" -wg "F:\DissAnalysis_2018\Hydrology\NEW_DATA\Resampled_Precip\prec09_clp_TIFF.tif"
This run may take on the order of 1 minutes to complete.
This estimate is very approximate.
Run time is highly uncertain as it depends on the complexity of the input data
and speed and memory of the computer. This estimate is based on our testing on
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.

job aborted:
[ranks] message

[0] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 0

[1] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 1

[2] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 2

[3] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 3

[4] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 4

[5] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 5

[6] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 6

[7] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 7

---- error analysis -----

[0-7] on EL-SANTO
AreaD8 aborted the job. abort code 5

**Comment by dtarb** [comment]
The problem is most likely that the file prec09_clp_TIFF.tif has a different number of rows and columns as CondDEM_FlowD8_2.tif.  If you look at the properties of these in a GIS you should be able to see this.  Sorry, this is a limitation of TauDEM, but rows and columns of input grids have to match.  Some GIS resampling functionality will need to be used to get the precip file the same as the flow direction file.

Line 126 of the aread8.cpp functions is where this error is triggered.
https://github.com/dtarb/TauDEM/blob/f927ca639a1834565a76cb3df5acbcd2909d6d0d/src/aread8.cpp#L126

A future release will write a more informative message, before just crashing.

**Comment by Jezzpeth** [comment]
Thank you, your answers have been quite helpful! Resampling using Extract by Mask did the trick. The D8 contributing area function ran without errors, although the river network in my study area has not been represented correctly. I may need to try burning in the streams, but let's see if I can figure it out myself before more questions!
