### ISSUE TITLE
D8 Distance to Stream failed

### ISSUE THREAD

**Issue by PDXChris** [dtarb/TauDEM#196]
I've been trying to run D8 Distance to Stream on a D8 flow direction grid in ArcGIS (tried on both 10.3 & Pro).  I extracted by mask (using a .tif of the contributing area) all the input layers so the rows and columns of input grids match.  Any thoughts on what I might be doing wrong (error message pasted below)?

For some reason, it is referring to the Output Distance to Stream grid (which seems to be causing the problem) as an input raster dataset in the error message.

Thanks!

####  ERROR MESSAGE ####
Running script D8 Distance To Streams...
Input D8 Flow Direction Grid: C:\Users\chrisp\Documents\temp\IDW_Scratch.gdb\flow_dir_d8_ebm
Input Stream Raster Grid: C:\Users\chrisp\Documents\temp\IDW_Scratch.gdb\rastercalc1_ebm
Threshold: 1
Number of Processes: 8
Output Distance To Streams: C:\Users\chrisp\Documents\temp\IDW_Scratch.gdb\Dist2Strm_ebm.tif
Command Line: mpiexec -n 8 D8HDistToStrm -p "C:\Users\chrisp\Documents\temp\IDW_Scratch.gdb\flow_dir_d8_ebm" -src "C:\Users\chrisp\Documents\temp\IDW_Scratch.gdb\rastercalc1_ebm" -dist "C:\Users\chrisp\Documents\temp\IDW_Scratch.gdb\Dist2Strm_ebm.tif" -thresh 1
job aborted:
[ranks] message

[0] terminated

[1] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 21, comm rank 1

[2] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 21, comm rank 2

[3] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 21, comm rank 3

[4] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 21, comm rank 4

[5] terminated

[6] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 21, comm rank 6

[7] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 21, comm rank 7

---- error analysis -----

[1-4,6-7] on LT21975
D8HDistToStrm aborted the job. abort code 21

---- error analysis -----
Calculate Statistics
Failed script D8 Distance To Streams...
Traceback (most recent call last):
  File "C:\Program Files\TauDEM\TauDEM5Arc\D8DistanceToStreams.py", line 54, in <module>
    arcpy.CalculateStatistics_management(dist)
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 16372, in CalculateStatistics
    raise e
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 16369, in CalculateStatistics
    retval = convertArcObjectToPythonObject(gp.CalculateStatistics_management(*gp_fixargs((in_raster_dataset, x_skip_factor, y_skip_factor, ignore_values, skip_existing, area_of_interest), True)))
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 496, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
 ERROR 000732: Input Raster Dataset: Dataset C:\Users\chrisp\Documents\temp\IDW_Scratch.gdb\Dist2Strm_ebm.tif does not exist or is not supported
Failed to execute (CalculateStatistics).
 Failed to execute (D8DistanceToStreams).
Failed at Monday, January 7, 2019 1:15:52 PM (Elapsed Time: 2.54 seconds)

**Comment by dtarb** [comment]
Save your results outside of a geodatabase (not in folder C:\Users\chrisp\Documents\temp\IDW_Scratch.gdb\Dist2Strm_ebm.tif).  TauDEM uses GDAL to read and write rasters, and the version compiled with TauDEM cannot write into an ESRI geodatabase.
