### ISSUE TITLE
can execute from command line but in ArcGIS10.6, newly installed, get error

### ISSUE THREAD

**Issue by sjskhalsa** [dtarb/TauDEM#199]
pit fill failed from toolbox installed in ArcGIS10.6, so I executed from command line no problem
the tried to execute flow direction and got same type of error as when tried pit fill:
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Raster Dataset: Dataset Z:\Local_Data\CHARIS Data\MJB_basins\MJB_basinsR3\CHARIS_DEM_Albers_3a_clipp.tif does not exist or is not supported
Failed to execute (CalculateStatistics).

working with fresh install of windows, arcgis and taudem

**Comment by dtarb** [comment]
Can you send more of the error message.  The part set relates to not being able to calculate statistics on the output.  Potential trouble spots are
- Z drive if it is a thumb drive sometimes does not work 
- space between CHARIS and Data in folder name may cause trouble

**Comment by sjskhalsa** [comment]
the strange thing is that the directory structure and file names have not changed since I last ran TauDEM in a VM on my macbook (the data files are in directories on the mac side). What's different is that the VM had to be reinstalled, with a new version of Windows and a new version of ArcGIS, so any environmental variables I had set up previously were lost.  From the ArcGIS geoprocessing results window I see the display of the taudem command line execution string, which if I paste into a command line in windows execute fine - same input/output files.

**Comment by dtarb** [comment]
I do not have any good ideas as have never worked with a VM on a mac.  I would suggest looking into permissions, odd characters in the names that may not get handled well across the interface etc.  Can you move the files into the VM (not in directories on the mac side).

**Comment by sjskhalsa** [comment]
I resolved the issue by moving the working directory into a drive under my documents on the windows side. Previously, the working directory was on the mac side and ArcGIS/ArcCatalog had it as a connected directory, but apparently couldn't write to it (although the taudem scripts run from the command line could!)

**Comment by sjskhalsa** [comment]
argh.  not resolved. started another project, got through pit removal, flow direction and contributing area from within ArcGIS10.6 but then at compute grid network I get the "does not exist or is not supported" error for a file that was created in a previous step!:
Traceback (most recent call last):
  File "C:\Program Files\TauDEM\TauDEM5Arc\GridNetwork.py", line 93, in <module>
    arcpy.CalculateStatistics_management(gord)
  File "c:\program files (x86)\arcgis\desktop10.6\arcpy\arcpy\management.py", line 17042, in CalculateStatistics
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Raster Dataset: Dataset \\Mac\Home\Documents\ArcGIS 10.6.1\MJB_basins_home\mjb_basinsr3\CHARIS_DEM_ver2_Albers_R3Bad8gord.tif does not exist or is not supported
Failed to execute (CalculateStatistics).
