### ISSUE TITLE
Error 000732: D-infinity Concentration Limited Accumulation

### ISSUE THREAD

**Issue by dlecourstessier** [dtarb/TauDEM#201]
Hi everyone !

First of all : I am using a PC computer, with Window. I have Arcgis 10.2 installed on it and I use the version 5.3 of TauDEM. 
 
I am trying to use the spatial analyse D-Infinity Concentration Limited Accumulation, but I alway get the famous error 000732. The thing is, I've already succeeded to do the analyse "Pit Remove" and " and "D-Infinity Flow direction", which is why I don't get the issue. **Also**, the error I get is : 

ERROR 000732: Input Raster Dataset: Dataset C:\Users\Labo_Maranger\Desktop\Daphnee\Elevation_MTq.tif does not exist or is not supported
Failed to execute (CalculateStatistics).

**But**, C:\Users\Labo_Maranger\Desktop\Daphnee\Elevation_MTq.tif  **is the output of the analyse, not the input.** 

Here is all the info I get : 
Executing: DInfConcLimitedAcccum Elevation_MTang.tif Reclass_Recl1 Reclass_Rout3 Reclass_Recl1 # 1 true 8 C:\Users\Labo_Maranger\Desktop\Daphnee\Elevation_MTq.tif C:\Users\Labo_Maranger\Desktop\Daphnee\Elevation_MTctpt.tif
Start Time: Thu Mar 07 15:00:24 2019
Running script DInfConcLimitedAcccum...Input D-Infinity Flow Direction Grid: C:\Users\Labo_Maranger\Desktop\Daphnee\Elevation_MTang.tif
Input Effective Runoff Weight Grid: C:\Users\Labo_Maranger\Documents\ArcGIS\Default.gdb\Reclass_Recl1
Input Disturbance Indicator Grid: C:\Users\Labo_Maranger\Documents\ArcGIS\Default.gdb\Reclass_Rout3
Input Decay Multiplier Grid: C:\Users\Labo_Maranger\Documents\ArcGIS\Default.gdb\Reclass_Recl1
Concentration Threshold: 1
Edge Contamination: true
Number of Processes: 8
Output Overland Flow Specific Discharge Grid: C:\Users\Labo_Maranger\Desktop\Daphnee\Elevation_MTq.tif
Output Concentration Grid: C:\Users\Labo_Maranger\Desktop\Daphnee\Elevation_MTctpt.tifCommand Line: mpiexec -n 8 AreaDinf -ang "C:\Users\Labo_Maranger\Desktop\Daphnee\Elevation_MTang.tif" -sca "C:\Users\Labo_Maranger\Desktop\Daphnee\Elevation_MTq.tif" -wg "C:\Users\Labo_Maranger\Documents\ArcGIS\Default.gdb\Reclass_Recl1"job aborted:
[ranks] message[0-1] terminated[2] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 21, comm rank 2[3-5] terminated[6] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 21, comm rank 6[7] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 21, comm rank 7---- error analysis -----[2,6-7] on LABO_MARANGERPC
AreaDinf aborted the job. abort code 21---- error analysis -----Calculate StatisticsFailed script DInfConcLimitedAcccum...Traceback (most recent call last):
 File "C:\Program Files\TauDEM\TauDEM5Arc\DinfConcenLimitAccum.py", line 86, in <module>
   arcpy.CalculateStatistics_management(q)
 File "c:\program files (x86)\arcgis\desktop10.2\arcpy\arcpy\management.py", line 13825, in CalculateStatistics
   raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Raster Dataset: Dataset C:\Users\Labo_Maranger\Desktop\Daphnee\Elevation_MTq.tif does not exist or is not supported
Failed to execute (CalculateStatistics).Failed to execute (DInfConcLimitedAcccum).
Failed at Thu Mar 07 15:00:26 2019 (Elapsed Time: 1,35 seconds)

Do you guys, have any idea how I could overcome this situation ?

Thanks a lot !

D

**Comment by dtarb** [comment]
Move the input grid files outside of a geodatabase.  I see above lines like Input Effective Runoff Weight Grid: C:\Users\Labo_Maranger\Documents\ArcGIS\Default.gdb\Reclass_Recl1

TauDEM uses the GDAL library that does not read grids inside a geodatabase.
