### ISSUE TITLE
Error 000732 Topographic Wetness Index

### ISSUE THREAD

**Issue by hoosiernew** [dtarb/TauDEM#207]
Hello everyone, 

I keep running into the famous Error 000732 while trying to run TWI. It states that "Error 000732: Input Raster Dataset: Dataset E:\GEOG 439\Lab6\elevtwi.tif does not exist or is not supported"

I have made sure that the Input is not located within a Geodatabase and the other suggestions that I found on previous similar posts. I will include the complete error. Any help would be greatly appreciated. Thank you very much!~

Executing: TopographicWetnessIndex "E:\GEOG 439\Lab6\elevsca.tif" "E:\GEOG 439\Lab6\elevslp.tif" 8 "E:\GEOG 439\Lab6\elevtwi.tif"
Start Time: Wed Nov 13 18:45:19 2019
Running script TopographicWetnessIndex...

Input Secific Catchment Area Grid: E:\GEOG 439\Lab6\elevsca.tif
Input Slope Grid: E:\GEOG 439\Lab6\elevslp.tif
Number of Processes: 8
Output Topographic Wetness Index Grid: E:\GEOG 439\Lab6\elevtwi.tif

Command Line: mpiexec -n 8 TWI -sca "E:\GEOG 439\Lab6\elevsca.tif" -slp "E:\GEOG 439\Lab6\elevslp.tif" -twi "E:\GEOG 439\Lab6\elevtwi.tif"

Calculate Statistics

Failed script TopographicWetnessIndex...

Traceback (most recent call last):
  File "C:\Program Files (x86)\ArcGIS\Desktop10.7\TauDEM\TauDEM5Arc\TopographicWetnessIndex.py", line 50, in <module>
    arcpy.CalculateStatistics_management(twi)
  File "c:\program files (x86)\arcgis\desktop10.7\arcpy\arcpy\management.py", line 17129, in CalculateStatistics
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Raster Dataset: Dataset E:\GEOG 439\Lab6\elevtwi.tif does not exist or is not supported
Failed to execute (CalculateStatistics).

Failed to execute (TopographicWetnessIndex).
Failed at Wed Nov 13 18:45:19 2019 (Elapsed Time: 0.26 seconds)

**Comment by dtarb** [comment]
Check the following
1. Does the file "elevtwi.tif" exist in your directory E:\GEOG 439\Lab6\.  It is possible that it may have been written but not recognized by the Calculate Statistics script.  If it is there, try to look at it in ArcGIS to see if there is anything obvious wrong.
2. Try run from the command line using 
mpiexec -n 8 TWI -sca "E:\GEOG 439\Lab6\elevsca.tif" -slp "E:\GEOG 439\Lab6\elevslp.tif" -twi "E:\GEOG 439\Lab6\elevtwi.tif"
Error messages for this may help with the problem.
3. As a long shot make sure E drive is not a thumb drive.  Writing to a thumb drive sometimes has difficulty.  (Though if this was the case previous TauDEM functions may have failed too).
