### ISSUE TITLE
ERROR 000539: Error running expression: rcexec() 

### ISSUE THREAD

**Issue by JINWen13** [dtarb/TauDEM#209]
Hello,

i have installed the Taudem version 5.3.7 Version on my computer and the arcmap version 10.2. it can be successful for doing the connectivity index, but when it was running the connectivity index targets, the error occurred. 
ERROR 000539: Error running expression: rcexec() 
Traceback (most recent call last):
  File "<expression>", line 1, in <module>
  File "<string>", line 5, in rcexec
  File "d:\program files (x86)\arcgis\desktop10.2\arcpy\arcpy\sa\Functions.py", line 4143, in Plus
    in_raster_or_constant2)
  File "d:\program files (x86)\arcgis\desktop10.2\arcpy\arcpy\sa\Utils.py", line 47, in swapper
    result = wrapper(*args, **kwargs)
  File "d:\program files (x86)\arcgis\desktop10.2\arcpy\arcpy\sa\Functions.py", line 4140, in Wrapper
    ["Plus", in_raster_or_constant1, in_raster_or_constant2])
RuntimeError: ERROR 000732: Input Raster: Dataset %accW.tif% does not exist or is not supported

Failed to execute (Computing C mean).
Failed at Wed Dec 25 17:03:44 2019 (Elapsed Time: 0.14 seconds)
Failed to execute (ConnectivityIndexTargets).
Failed at Wed Dec 25 17:03:44 2019 (Elapsed Time: 6.41 seconds)
I have no idea for this error.
Could anyone give me some suggestions?

**Comment by JINWen13** [comment]
I

**Comment by JINWen13** [comment]
I have solved this issue.
