### ISSUE TITLE
Parameters Execution Error: Runtime error Traceback

### ISSUE THREAD

**Issue by Lizachash** [dtarb/TauDEM#246]
Hi, 

I just can't figure it out, I'm trying to use the toolbox in Arcmap, but when I put in my DEM file I get an error message saying

"updateParameters Execution Error: Runtime error Traceback (most recent call last): File "C:\Program Files\TauDEM\TauDEM5Arc\TauDEM Tools.tbx#PitRemove.UpdateParameters.py", line 4, in File "C:\Program Files\TauDEM\TauDEM5Arc\TauDEM Tools.tbx#PitRemove.UpdateParameters.py", line 28, in updateParameters UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 21: ordinal not in range(128) "

![image](https://user-images.githubusercontent.com/118911829/203572920-c340d2d2-c131-45b2-aeb5-f4a7e01c530f.png)

Thank you,
Liza

**Comment by dtarb** [comment]
Liza,
I suggest you check the folder path where your input file is and see if it has any unusual or special characters.  The error message is at a location in the code where it is trying to read the input file name and insert a "fel" into it to use as the default output name.  The error suggests difficulty working with a character in this file name.  This can occur if there are foreign language characters, special characters, or something else in the file name.  The solution would be to change the file/folder name.  (Sorry if this is inconvenient).

Another clue for this is that while the window above has an input file name, it does not have an output file name, suggesting that this part of the code failed.

**Comment by Lizachash** [comment]
Hi again David, 

Thank you for your quick answer, it was a simple change of a letter in the folder name, but I still run into problems which I don't really understand. 

Now I can put in my file, but I get the error code 000732, that the dataset does not exist or are supported, I don't really get why because I can use it with every other tool, is there something that I am missing? I looked at the PDF- file and your explanation video and I still don't get it. Do you have any suggestions? I'll put in a screenshot of it as well. Excuse my lack of knowledge.

![image](https://user-images.githubusercontent.com/118911829/203730971-32556851-3cb7-4cff-a88e-31324c45bbad.png)

Thank you so much!

**Comment by dtarb** [comment]
This error indicates that the Taudem command did not execute properly so the steps in the script after it are unable to find and add the output file to the map.  This is likely an installation or path problem associated with one of the TauDEM library dependencies.  The screen shot above does not hold enough information to pinpoint the problem and I suggest you try run from the command line to sort out.  

1. Open a command prompt
2. At the prompt type the text on the 8th line of the screen shot above that starts  "mpiexec -n 1 pitremove -z ..."
3. Look at the errors you get and see if they suggest what may be wrong.  Feel free to send them to me.

Potential problems are.  
- mpiexec not found, meaning that the path to mpi did not get set up in the installation
- pitremove not found, meaning that the path to Taudem did not get set up in the installation
- A GDAL library problem

Note that the 8 in the command line above indicates the number of processors.  For debugging I would switch to 1, though you will likely get the same responses with both 8 and 1.

There is more information on running from the command line in the command line guide at http://hydrology.usu.edu/taudem/taudem5/TauDEM53CommandLineGuide.pdf.  This has a bit of information on setting and fixing paths if needed.
