### ISSUE TITLE
Pit Remove failed

### ISSUE THREAD

**Issue by priyatowin** [dtarb/TauDEM#250]
I've been trying to run Pit remove tool from the TAUDEM toolset in ArcGIS (tried on both 10.3 & Pro). Any thoughts on what I might be doing wrong (error message pasted below)?

Thanks!

**Error Message**

Executing: PitRemove "D:\Data for Analysis\Gurgoan\Cartosat_DEM\Carto_Gurugoan_ws1.tif" # # 8 "D:\Data for Analysis\Gurgoan\Cartosat_DEM\Carto_Gurugoan_ws1_pitl.tif"
Start Time: Fri Mar 24 11:19:26 2023
Running script PitRemove...

Input Elevation file: D:\Data for Analysis\Gurgoan\Cartosat_DEM\Carto_Gurugoan_ws1.tif
Considering4way: 
 Number of Processes: 8
Output Pit Removed Elevation file: D:\Data for Analysis\Gurgoan\Cartosat_DEM\Carto_Gurugoan_ws1_pitl.tif

Command Line: mpiexec -n 8 pitremove -z "D:\Data for Analysis\Gurgoan\Cartosat_DEM\Carto_Gurugoan_ws1.tif" -fel "D:\Data for Analysis\Gurgoan\Cartosat_DEM\Carto_Gurugoan_ws1_pitl.tif"

Calculate Statistics

Failed script PitRemove...

Traceback (most recent call last):
  File "C:\Program Files\TauDEM\TauDEM5Arc\PitRemove.py", line 61, in <module>
    arcpy.CalculateStatistics_management(outFile)
  File "c:\program files (x86)\arcgis\desktop10.4\arcpy\arcpy\management.py", line 14811, in CalculateStatistics
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Raster Dataset: Dataset D:\Data for Analysis\Gurgoan\Cartosat_DEM\Carto_Gurugoan_ws1_pitl.tif does not exist or is not supported
Failed to execute (CalculateStatistics).

Failed to execute (PitRemove).
Failed at Fri Mar 24 11:19:27 2023 (Elapsed Time: 0.25 seconds)

**Comment by dtarb** [comment]
I can not see anything wrong.  The error message is that the output file can not have statistics calculated (because it was not written by the earlier TauDEM command).  To see what is actually going wrong open a command prompt (start cmd) and try the function from the command line

mpiexec -n 8 pitremove -z "D:\Data for Analysis\Gurgoan\Cartosat_DEM\Carto_Gurugoan_ws1.tif" -fel "D:\Data for Analysis\Gurgoan\Cartosat_DEM\Carto_Gurugoan_ws1_pitl.tif"

This should give more detailed errors that are not passed through to the ArcGIS interface.

Some possible problems
- TauDEM installation or path.  Have you run TauDEM before on this computer?  Did all the components (GDAL is sometimes problematic) get installed right.
- A limitation of the D drive.  Sometimes MPI has problems with thumb (small USB) or network drives.
- Something wrong with the input file (too big, not a grid TauDEM can read)
