### ISSUE TITLE
ERROR TauDEM 000732

### ISSUE THREAD

**Issue by tabtab26** [dtarb/TauDEM#251]
Hi, 
I just started to work with TauDEM on ArcGisPro, but there is always the same error accuring:

Traceback (most recent call last):
  File "C:\Program Files\TauDEM\TauDEM5Arc\PitRemove.py", line 51, in <module>
    ﻿
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 20780, in CalculateStatistics
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 20777, in CalculateStatistics
    retval = convertArcObjectToPythonObject(gp.CalculateStatistics_management(*gp_fixargs((in_raster_dataset, x_skip_factor, y_skip_factor, ignore_values, skip_existing, area_of_interest), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 512, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
 ERROR 000732: Input Raster Dataset: Dataset C:\Users\Giub\Documents\ArcGIS\Projects\ProbeTAuDEMLogan\Logan\loganfel.tif does not exist or is not supported
Failed to execute (CalculateStatistics).

I already reinstalled TauDEM, but this did not solve the problem. I also tried to use different DTMs, and different Tools from the Toolbox, but ArcGIS shows me always the same error. 
I would be glad, if someone could help me.

**Comment by dtarb** [comment]
@tabtab26.  The error message indicates that the output file was not written so is missing when there is an attempt to calculate statistics on it.  To try to see what is actually going wrong open a command prompt (start cmd) and try the function from the command line

mpiexec -n 1 pitremove inputfilename.tif

This should give more detailed errors that should help.

Some possible problems

- TauDEM installation or path. Did all the components get installed right.  GDAL or MPI sometimes cause problems.
- A limitation of the where the file is. Sometimes MPI has problems with thumb (small USB) or network drives if the files are there.
- Something wrong with the input file (too big, not a grid TauDEM can read)

I would guess an installation/path issue in your case, since this is the first time you are trying it.  See also Command line documentation at https://hydrology.usu.edu/taudem/taudem5/documentation.html where there is more information on running from the command line and debugging.

**Comment by tabtab26** [comment]
Hello dtarb, 
thank you for the answer!
I`m not really good with all that stuff, so i tried a different way by running the R code. 
The same error accured, it looks like there is a problem with MPI. Do you know how I can fix that? Thank you for the help!

system("mpiexec -n 8 pitremove -z logan.tif -fel loganfel.tif")

Aborting: mpi appplication on LAPTOP-27QV4NGJ is unable to connect to the smpd manager on (null):65292 error 1722

Aborting: mpi appplication on LAPTOP-27QV4NGJ is unable to connect to the smpd manager on (null):65290 error 1722

job aborted:
[ranks] message

[4] fatal error
Fatal error in MPI_Init: Other MPI error, error stack:
MPI_Init(argc_p=0x0000000000000000, argv_p=0x0000000000000000) failed
Der RPC-Server ist nicht verfÃ¼gbar.  (errno 1722)

job aborted:
[ranks] message

[6] fatal error
Fatal error in MPI_Init: Other MPI error, error stack:
MPI_Init(argc_p=0x0000000000000000, argv_p=0x0000000000000000) failed
Der RPC-Server ist nicht verfÃ¼gbar.  (errno 1722)

Aborting: mpi appplication on LAPTOP-27QV4NGJ is unable to connect to the smpd manager on (null):65293 error 1722

Aborting: mpi appplication on LAPTOP-27QV4NGJ is unable to connect to the smpd manager on (null):65289 error 1722

job aborted:
[ranks] message

[3] fatal error
Fatal error in MPI_Init: Other MPI error, error stack:
MPI_Init(argc_p=0x0000000000000000, argv_p=0x0000000000000000) failed
Der RPC-Server ist nicht verfÃ¼gbar.  (errno 1722)

job aborted:
[ranks] message

[7] fatal error
Fatal error in MPI_Init: Other MPI error, error stack:
MPI_Init(argc_p=0x0000000000000000, argv_p=0x0000000000000000) failed
Der RPC-Server ist nicht verfÃ¼gbar.  (errno 1722)

Aborting: mpi appplication on LAPTOP-27QV4NGJ is unable to connect to the smpd manager on (null):65294 error 1722

job aborted:
[ranks] message

[2] fatal error
Fatal error in MPI_Init: Other MPI error, error stack:
MPI_Init(argc_p=0x0000000000000000, argv_p=0x0000000000000000) failed
Der RPC-Server ist nicht verfÃ¼gbar.  (errno 1722)

Aborting: mpi appplication on LAPTOP-27QV4NGJ is unable to connect to the smpd manager on (null):65295 error 1722

job aborted:
[ranks] message

[1] fatal error
Fatal error in MPI_Init: Other MPI error, error stack:
MPI_Init(argc_p=0x0000000000000000, argv_p=0x0000000000000000) failed
Der RPC-Server ist nicht verfÃ¼gbar.  (errno 1722)

Aborting: mpi appplication on LAPTOP-27QV4NGJ is unable to connect to the smpd manager on (null):65291 error 1722

job aborted:
[ranks] message

[5] fatal error
Fatal error in MPI_Init: Other MPI error, error stack:
MPI_Init(argc_p=0x0000000000000000, argv_p=0x0000000000000000) failed
Der RPC-Server ist nicht verfÃ¼gbar.  (errno 1722)

Aborting: mpi appplication on LAPTOP-27QV4NGJ is unable to connect to the smpd manager on (null):65296 error 1722

job aborted:
[ranks] message

[0] fatal error
Fatal error in MPI_Init: Other MPI error, error stack:
MPI_Init(argc_p=0x0000000000000000, argv_p=0x0000000000000000) failed
Der RPC-Server ist nicht verfÃ¼gbar.  (errno 1722)
[1] 0
> fel=raster("loganfel.tif")
Fehler in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file. (file does not exist)
Zusätzlich: Warnmeldung:
C:/Users/Giub/Desktop/Logan/loganfel.tif: No such file or directory (GDAL error 4) 
> plot(fel)
Fehler in h(simpleError(msg, call)) : 
  Fehler bei der Auswertung des Argumentes 'x' bei der Methodenauswahl für Funktion 'plot': Objekt 'fel' nicht gefunden
