### ISSUE TITLE
ERROR 000732: Input Raster Dataset #19

### ISSUE THREAD

**Issue by dong-boo** [dtarb/TauDEM#252]
I download and installed TauDEM for examining the capability of the tool to edit the DEM. I extracted and imported the elevation to ArcMap and ran the 'pit remove' tool. When it finished running it shows error message;

Process started:
Executing: PitRemove logan.tif # # 8 C:\Users\HUAWEI\Downloads\logan\loganfel.tif
Start Time: Sun Apr 02 00:00:12 2023
Running script PitRemove...

Input Elevation file: C:\Users\HUAWEI\Downloads\logan\logan.tif
Considering4way: 
 Number of Processes: 8
Output Pit Removed Elevation file: C:\Users\HUAWEI\Downloads\logan\loganfel.tif

Command Line: mpiexec -n 8 pitremove -z "C:\Users\HUAWEI\Downloads\logan\logan.tif" -fel "C:\Users\HUAWEI\Downloads\logan\loganfel.tif"

Calculate Statistics

Traceback (most recent call last):
  File "C:\Program Files\TauDEM\TauDEM5Arc\PitRemove.py", line 61, in <module>
    arcpy.CalculateStatistics_management(outFile)
  File "c:\program files (x86)\arcgis\desktop10.2\arcpy\arcpy\management.py", line 13271, in CalculateStatistics
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Raster Dataset: Dataset C:\Users\HUAWEI\Downloads\logan\loganfel.tif does not exist or is not supported
Failed to execute (CalculateStatistics).

Failed to execute (PitRemove).
![image](https://user-images.githubusercontent.com/129612074/229301470-7032c73d-8d47-4d07-a162-9841a1bb5489.png)
I could not process further. Any help would be greatly appreciated.

Regards,
Dongdong

**Comment by dtarb** [comment]
@dong-boo it looks like in the screen shot above your PitRemove function worked on the command line, in that time use is reported.  Check of you have the output file loganfel.tif.  I am not able to see in the ArcGIS error messages you have presented why it may not have worked in ArcGIS.  

In the screen shot above for D8FlowDir you need to specify the name of the input file after -fel, i.e.
mpiexec -n 8 D8Flowdir -p loganp.tif -sd8 logansd8.tif -fel loganfel.tif
The error you received was because loganfel.tif was not given as input.
