### ISSUE TITLE
Accommodate special characters in path names

### ISSUE THREAD

**Issue by dtarb** [dtarb/TauDEM#58]
A user reported an error due to the following file path 
C:\Users\Constance Fastré\Desktop\DEM
Note accent on the e.

**Comment by dtarb** [comment]
A user reported the following error.
ERROR 
updateParameters Execution Error: Runtime error Traceback (most recent call last): File "C:\Program Files\TauDEM\TauDEM5Arc\TauDEM Tools.tbx#PitRemove.UpdateParameters.py", line 4, in File "C:\Program Files\TauDEM\TauDEM5Arc\TauDEM Tools.tbx#PitRemove.UpdateParameters.py", line 27, in updateParameters UnicodeEncodeError: 'ascii' codec can't encode characters in position 38-39: ordinal not in range(128)

I responded "As a work around check the names of the files and the folder path being used and if possible remove anything like an accent or other non-simple character, and see if that fixes it."
